### ISSUE TITLE
Viscosity changes 

### ISSUE THREAD

**Issue by sb926** [OlympusMonds/lithospheric_modelling_recipe#9]
Hey Luke,
I ran another model with very basic passive margin set up and there is again a trend for the oceanic lithosphere to become very reduced in viscosity values after the thermal equilibration phase is completed. It doesn't look plausible and I'm thinking I will have to change the values assigned for the asthenosphere. 

My boundary conditions are the same as the example set-up, 1cm pull at each side of model. Although the oceanic/continental lithosphere looks like different materials they have same properties. I was considering using slightly different characteristics but haven't introduced this yet. I commented out the random damage.

Model set-up
![passive_margin_setup_15jan](https://cloud.githubusercontent.com/assets/12419983/12345363/f61fbc1c-bb9b-11e5-96bd-b6eff91aced5.png)
Viscosity field first timestep post-thermal equilibration
![passive_margin_viscosityfield_firsttimestep](https://cloud.githubusercontent.com/assets/12419983/12345382/271f05a2-bb9c-11e5-8d7f-c271e0c7f316.png)
Final viscosity field at ~ 3.05 Myr
![passive_margin_viscosityfield_final_timestep](https://cloud.githubusercontent.com/assets/12419983/12345389/421c9b6c-bb9c-11e5-98da-a3fe325cacfd.png)

Velocity field first timestep
![passive_margin_velocityfield_firsttimestep](https://cloud.githubusercontent.com/assets/12419983/12345407/845b9fdc-bb9c-11e5-8a88-ce77d253db62.png)
Velocity field final timestep
![passive_margin_velocityfield_final_timestep](https://cloud.githubusercontent.com/assets/12419983/12345413/93d9d9ec-bb9c-11e5-9df9-f4909c0f1c9a.png)

Materials input file
[lmrMaterials.txt](https://github.com/OlympusMonds/lithospheric_modelling_recipe/files/91360/lmrMaterials.txt)

**Comment by OlympusMonds** [comment]
Sarah and I spoke about this in person.
The summary:
1) The thermal equilibration, by default, goes for 1 billion years. This is not appropriate for a model with oceanic lithosphere in it. By defining a thermal BC within a triangular (or whatever) shape under the oceanic lithosphere would therefore squish the geotherm, and keep it "naturally" hot while the thermal equilibration happens. Why would we even want to thermally equilibrate in this context? It's much easier than defining the geotherm everywhere in the model by hand.
2) The velocities probably are caused by the initial model not being in isostatic equilibrium, and so on the first timestep, it tries to relax into it. After a few timesteps, this will chill out.
